### ISSUE TITLE
Documentation for Containers and pulling from a local registry are incorrect

### ISSUE THREAD

**Issue by 9strands** [Juniper/contrail-tripleo-heat-templates#118]
Hi, Contrail team,

  Working on an OSP13 + Contrail 5.0.2 update.  There's some issues with the dev_nodes MD file here:
https://github.com/Juniper/contrail-tripleo-heat-templates/blob/stable/queens/

1. Doco error

https://github.com/Juniper/contrail-tripleo-heat-templates/blob/stable/queens/dev_notes.md
Line 563: "DockerNeutronConfigImage contrail-openstack-neutron-init"
is incorrect.  Creating a container with this name to replace the OSP13 DockerNeutronConfigImage fails, causing a "Line23: /usr/bin/puppet file or directory not found" error in Step2 of the deployer which is a pain to debug.  It is correct in the shell script pulling images.

2. Instructions from pulling Containers directly from a local Container Registry do not exist, but should be added (Satellite 6.4, Quay, Nexus, etc as most enterprises will have their own) need to be included (also here - https://www.juniper.net/documentation/en_US/contrail5.0/topics/concept/Deploying-Contrail-with-RedHatOpenStack.html).  Below are the instructions for how to do that.  

Note that "DockerContrailNeutronPluginImageName" is different - for some reason it doesn't recreate the Image URL for docker pull the way the other "DockerContrail" URLs do, so set it the same way as for the OSP13 containers:

In contrail-services.yaml, set the following  
```  ContrailRegistryInsecure: true
  DockerInsecureRegistryAddress: satellite6.lab.example.net:5000
  ContrailRegistryCertUrl: http://satellite6.lab.example.net/pub/katello-server-ca.crt
  ContrailRegistry: satellite6.lab.example.net:5000
  ContrailImageTag: 5.0.3-0.493-rhel-queens
```

In the overcloud-images.yml file (forget uploading the images to director, pull them directly from the local Container registry):

```
parameter_defaults:
  ...
  DockerContrailAnalyticsAlarmGenImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-alarm-gen
  DockerContrailAnalyticsApiImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-api
  DockerContrailAnalyticsCollectorImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-collector
  DockerContrailAnalyticsQueryEngineImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-query-engine
  DockerContrailAnalyticsSnmpCollectorImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-snmp-collector
  DockerContrailAnalyticsTopologyImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-snmp-topology
  DockerContrailAnalyticsTopologyImageName_5_0: satellite6_lab_example_net-contrail_5_x_registry-contrail-analytics-topology
  DockerContrailConfigApiImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-config-api
  DockerContrailConfigDevicemgrImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-config-devicemgr
  DockerContrailConfigSchemaImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-config-schema
  DockerContrailConfigSvcmonitorImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-config-svcmonitor
  DockerContrailControlControlImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-control-control
  DockerContrailControlDnsImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-control-dns
  DockerContrailControlNamedImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-control-named
  DockerContrailWebuiJobImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-webui-job
  DockerContrailWebuiWebImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-controller-webui-web
  DockerContrailCassandraImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-external-cassandra
  DockerContrailKafkaImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-external-kafka
  DockerContrailRabbitmqImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-external-rabbitmq
  DockerContrailRedisImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-external-redis
  DockerContrailZookeeperImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-external-zookeeper
  DockerContrailNodeInitImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-node-init
  DockerContrailNodemgrImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-nodemgr
  DockerContrailNovaPluginImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-openstack-compute-init
  DockerContrailHeatPluginImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-openstack-heat-init
  #DockerNeutronConfigImage: satellite6.lab.example.net:5000/satellite6_lab_example_net-contrail_5_x_registry-contrail-neutron-init:5.0.2-0.360-rhel-queens ### LEAVE OSP13 DEFAULT!
  DockerContrailNeutronPluginImageName: satellite6.lab.example.net:5000/satellite6_lab_example_net-contrail_5_x_registry-contrail-openstack-neutron-init:5.0.3-0.493-rhel-queens ### NOTE: THIS ONE IS UNIQUE
  DockerContrailVrouterAgentContainerName: satellite6_lab_example_net-contrail_5_x_registry-contrail-vrouter-agent
  DockerContrailVrouterAgentDpdkContainerName: satellite6_lab_example_net-contrail_5_x_registry-contrail-vrouter-agent-dpdk
  DockerContrailVrouterAgentImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-vrouter-agent
  DockerContrailVrouterKernelInitImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-vrouter-kernel-init
  DockerContrailVrouterKernelInitDpdkImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-vrouter-kernel-init-dpdk
  DockerContrailStatusImageName: satellite6_lab_example_net-contrail_5_x_registry-contrail-status
  DockerInsecureRegistryAddress:
  - satellite6.lab.example.net:5000
```

If you would like for me to submit changes to the repo for those files to add in these bits, I am happy to do so.

-John
